# Generated by Selenium IDE
from xml.dom.minidom import Element
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBoce01():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_boce01(self):
    self.driver.get("https://www.boce.com/dns")
    self.driver.find_element(By.NAME, "host").click()
    self.driver.find_element(By.NAME, "host").send_keys("www.hbzb666.com")    
    self.driver.find_element(By.CSS_SELECTOR, ".main02b2:nth-child(4)").click()
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.NAME, "host").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".rs_chart")))

    element = self.driver.find_element_by_class_name("rs_chart")

    
    
  
